// <auto-generated />
using System;
using EFDoubleMigrationsTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDoubleMigrationsTest.Migrations
{
    [DbContext(typeof(FeatureADbContext))]
    partial class FeatureADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFDoubleMigrationsTest.Models.ModelA", b =>
                {
                    b.Property<Guid>("ModelAId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ModelAId");

                    b.ToTable("ModelAs");
                });
#pragma warning restore 612, 618
        }
    }
}
